#server:
                    #  port: 8889
                    #spring:
                    #  application:
                    #    name: rabbitmq-fanout
                    #  rabbitmq:
                    #    host: 127.0.0.1
                    #    port: 5672
                    #    username: guest
                    #    password: guest